[package]
name = "missile-sim"
version = "0.1.0"
edition = "2024"

[lib]
name = "missile_sim"
path = "src/lib.rs"

[[bin]]
name = "plot"
path = "src/bin/plot.rs"

[[bin]]
name = "debug"
path = "src/bin/debug.rs"

[[bin]]
name = "data"
path = "src/bin/generate_data.rs"

[[bin]]
name = "game"
path = "src/bin/game.rs"

[dependencies]
plotters = "0.3.7"
nalgebra = "0.34.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
raylib = "5.5.1"
rand = "0.10.0-rc.0"
rayon = "1.11.0"
bevy = "0.16.0"

# Add this profile to speed up compilation
[profile.dev]
opt-level = 1  # Enable basic optimization

[profile.dev.package."*"]
opt-level = 3  # Max optimize dependencies
