[package]
name = "missile-sim"
version = "0.1.0"
edition = "2024"

[lib]
name = "missile_sim"
path = "src/lib.rs"

[[bin]]
name = "ms"
path = "src/bin/cli.rs"

[[bin]]
name = "plot"
path = "src/bin/plot.rs"

[[bin]]
name = "data"
path = "src/bin/generate_data.rs"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
plotters = "0.3.7"
nalgebra = "0.34.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
rand = "0.10.0-rc.0"
rayon = "1.11.0"